plugins { id 'com.android.application' }
android {
    namespace 'com.miniscreen.minilock'
    compileSdk 36
    defaultConfig {
        applicationId 'com.miniscreen.minilock'
        minSdk 26
        targetSdk 36
        versionCode 19
        versionName '0.0.19'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
